namespace alphaVote.Views
{
    partial class FrmDashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmDashboard));
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.lblTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.BodyPanel = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuPages1 = new Bunifu.UI.WinForms.BunifuPages();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.tabPage5 = new System.Windows.Forms.TabPage();
            this.SidebarPanel = new System.Windows.Forms.TableLayoutPanel();
            this.BtnLogout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ImgUserImage = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.lblUsername = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnEvents = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCandidates = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnVoters = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnResults = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnSettings = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.IcoLogo = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.BtnMinimize = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.BtnExit = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.bunifuFormDock2 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.TitleBarPanel = new System.Windows.Forms.TableLayoutPanel();
            this.HomePagePanel = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel4 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tabPage6 = new System.Windows.Forms.TabPage();
            this.BodyPanel.SuspendLayout();
            this.bunifuPages1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.SidebarPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ImgUserImage)).BeginInit();
            this.TitleBarPanel.SuspendLayout();
            this.HomePagePanel.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = this.lblTitle;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // lblTitle
            // 
            this.lblTitle.AllowParentOverrides = false;
            this.lblTitle.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblTitle.AutoEllipsis = false;
            this.lblTitle.AutoSize = false;
            this.lblTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Location = new System.Drawing.Point(42, 0);
            this.lblTitle.Margin = new System.Windows.Forms.Padding(0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitle.Size = new System.Drawing.Size(713, 41);
            this.lblTitle.TabIndex = 12;
            this.lblTitle.Text = "Alpha Vote System";
            this.lblTitle.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BodyPanel
            // 
            this.BodyPanel.ColumnCount = 2;
            this.BodyPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.BodyPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.BodyPanel.Controls.Add(this.bunifuPages1, 1, 0);
            this.BodyPanel.Controls.Add(this.SidebarPanel, 0, 0);
            this.BodyPanel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.BodyPanel.Location = new System.Drawing.Point(0, 46);
            this.BodyPanel.Name = "BodyPanel";
            this.BodyPanel.RowCount = 1;
            this.BodyPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.BodyPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 404F));
            this.BodyPanel.Size = new System.Drawing.Size(839, 404);
            this.BodyPanel.TabIndex = 13;
            // 
            // bunifuPages1
            // 
            this.bunifuPages1.Alignment = System.Windows.Forms.TabAlignment.Left;
            this.bunifuPages1.AllowTransitions = false;
            this.bunifuPages1.Controls.Add(this.tabPage1);
            this.bunifuPages1.Controls.Add(this.tabPage2);
            this.bunifuPages1.Controls.Add(this.tabPage3);
            this.bunifuPages1.Controls.Add(this.tabPage4);
            this.bunifuPages1.Controls.Add(this.tabPage5);
            this.bunifuPages1.Controls.Add(this.tabPage6);
            this.bunifuPages1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPages1.Location = new System.Drawing.Point(183, 16);
            this.bunifuPages1.Margin = new System.Windows.Forms.Padding(16);
            this.bunifuPages1.Multiline = true;
            this.bunifuPages1.Name = "bunifuPages1";
            this.bunifuPages1.Padding = new System.Drawing.Point(0, 0);
            this.bunifuPages1.Page = this.tabPage1;
            this.bunifuPages1.PageIndex = 0;
            this.bunifuPages1.PageName = "tabPage1";
            this.bunifuPages1.PageTitle = "tabPage1";
            this.bunifuPages1.SelectedIndex = 0;
            this.bunifuPages1.Size = new System.Drawing.Size(640, 372);
            this.bunifuPages1.TabIndex = 16;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bunifuPages1.Transition = animation1;
            this.bunifuPages1.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(38)))), ((int)(((byte)(45)))));
            this.tabPage1.Controls.Add(this.HomePagePanel);
            this.tabPage1.Location = new System.Drawing.Point(23, 4);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(16);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(613, 364);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "tabPage1";
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(38)))), ((int)(((byte)(45)))));
            this.tabPage2.Location = new System.Drawing.Point(23, 4);
            this.tabPage2.Margin = new System.Windows.Forms.Padding(16);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(613, 364);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            // 
            // tabPage3
            // 
            this.tabPage3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(38)))), ((int)(((byte)(45)))));
            this.tabPage3.Location = new System.Drawing.Point(23, 4);
            this.tabPage3.Margin = new System.Windows.Forms.Padding(16);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage3.Size = new System.Drawing.Size(613, 364);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "tabPage3";
            // 
            // tabPage4
            // 
            this.tabPage4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(38)))), ((int)(((byte)(45)))));
            this.tabPage4.Location = new System.Drawing.Point(23, 4);
            this.tabPage4.Margin = new System.Windows.Forms.Padding(16);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage4.Size = new System.Drawing.Size(613, 364);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "tabPage4";
            // 
            // tabPage5
            // 
            this.tabPage5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(38)))), ((int)(((byte)(45)))));
            this.tabPage5.Location = new System.Drawing.Point(23, 4);
            this.tabPage5.Margin = new System.Windows.Forms.Padding(16);
            this.tabPage5.Name = "tabPage5";
            this.tabPage5.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage5.Size = new System.Drawing.Size(613, 364);
            this.tabPage5.TabIndex = 4;
            this.tabPage5.Text = "tabPage5";
            // 
            // SidebarPanel
            // 
            this.SidebarPanel.ColumnCount = 2;
            this.SidebarPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.SidebarPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.SidebarPanel.Controls.Add(this.BtnLogout, 0, 7);
            this.SidebarPanel.Controls.Add(this.ImgUserImage, 0, 0);
            this.SidebarPanel.Controls.Add(this.lblUsername, 1, 0);
            this.SidebarPanel.Controls.Add(this.BtnHome, 0, 1);
            this.SidebarPanel.Controls.Add(this.BtnEvents, 0, 2);
            this.SidebarPanel.Controls.Add(this.BtnCandidates, 0, 3);
            this.SidebarPanel.Controls.Add(this.BtnVoters, 0, 4);
            this.SidebarPanel.Controls.Add(this.BtnResults, 0, 5);
            this.SidebarPanel.Controls.Add(this.BtnSettings, 0, 6);
            this.SidebarPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SidebarPanel.Location = new System.Drawing.Point(3, 16);
            this.SidebarPanel.Margin = new System.Windows.Forms.Padding(3, 16, 3, 16);
            this.SidebarPanel.Name = "SidebarPanel";
            this.SidebarPanel.RowCount = 8;
            this.SidebarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.SidebarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.SidebarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.SidebarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.SidebarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.SidebarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.SidebarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.SidebarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.5F));
            this.SidebarPanel.Size = new System.Drawing.Size(161, 372);
            this.SidebarPanel.TabIndex = 17;
            // 
            // BtnLogout
            // 
            this.BtnLogout.AllowAnimations = true;
            this.BtnLogout.AllowMouseEffects = true;
            this.BtnLogout.AllowToggling = false;
            this.BtnLogout.AnimationSpeed = 200;
            this.BtnLogout.AutoGenerateColors = false;
            this.BtnLogout.AutoRoundBorders = false;
            this.BtnLogout.AutoSizeLeftIcon = true;
            this.BtnLogout.AutoSizeRightIcon = true;
            this.BtnLogout.BackColor = System.Drawing.Color.Transparent;
            this.BtnLogout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnLogout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnLogout.BackgroundImage")));
            this.BtnLogout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogout.ButtonText = "Logout";
            this.BtnLogout.ButtonTextMarginLeft = 0;
            this.BtnLogout.ColorContrastOnClick = 45;
            this.BtnLogout.ColorContrastOnHover = 45;
            this.SidebarPanel.SetColumnSpan(this.BtnLogout, 2);
            this.BtnLogout.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.BtnLogout.CustomizableEdges = borderEdges4;
            this.BtnLogout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnLogout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLogout.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnLogout.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnLogout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BtnLogout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnLogout.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnLogout.ForeColor = System.Drawing.Color.White;
            this.BtnLogout.IconLeft = null;
            this.BtnLogout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnLogout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLogout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnLogout.IconMarginLeft = 11;
            this.BtnLogout.IconPadding = 10;
            this.BtnLogout.IconRight = null;
            this.BtnLogout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnLogout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnLogout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnLogout.IconSize = 25;
            this.BtnLogout.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnLogout.IdleBorderRadius = 0;
            this.BtnLogout.IdleBorderThickness = 0;
            this.BtnLogout.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnLogout.IdleIconLeftImage = null;
            this.BtnLogout.IdleIconRightImage = null;
            this.BtnLogout.IndicateFocus = false;
            this.BtnLogout.Location = new System.Drawing.Point(4, 326);
            this.BtnLogout.Margin = new System.Windows.Forms.Padding(4);
            this.BtnLogout.Name = "BtnLogout";
            this.BtnLogout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnLogout.OnDisabledState.BorderRadius = 0;
            this.BtnLogout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogout.OnDisabledState.BorderThickness = 1;
            this.BtnLogout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnLogout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnLogout.OnDisabledState.IconLeftImage = null;
            this.BtnLogout.OnDisabledState.IconRightImage = null;
            this.BtnLogout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnLogout.onHoverState.BorderRadius = 0;
            this.BtnLogout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogout.onHoverState.BorderThickness = 1;
            this.BtnLogout.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.BtnLogout.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnLogout.onHoverState.IconLeftImage = null;
            this.BtnLogout.onHoverState.IconRightImage = null;
            this.BtnLogout.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnLogout.OnIdleState.BorderRadius = 0;
            this.BtnLogout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogout.OnIdleState.BorderThickness = 1;
            this.BtnLogout.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnLogout.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnLogout.OnIdleState.IconLeftImage = null;
            this.BtnLogout.OnIdleState.IconRightImage = null;
            this.BtnLogout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnLogout.OnPressedState.BorderRadius = 0;
            this.BtnLogout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnLogout.OnPressedState.BorderThickness = 1;
            this.BtnLogout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnLogout.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnLogout.OnPressedState.IconLeftImage = null;
            this.BtnLogout.OnPressedState.IconRightImage = null;
            this.BtnLogout.Size = new System.Drawing.Size(153, 42);
            this.BtnLogout.TabIndex = 19;
            this.BtnLogout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnLogout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnLogout.TextMarginLeft = 0;
            this.BtnLogout.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnLogout.UseDefaultRadiusAndThickness = true;
            this.BtnLogout.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // ImgUserImage
            // 
            this.ImgUserImage.AllowFocused = false;
            this.ImgUserImage.AutoSizeHeight = false;
            this.ImgUserImage.BackColor = System.Drawing.Color.Transparent;
            this.ImgUserImage.BorderRadius = 20;
            this.ImgUserImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ImgUserImage.Image = ((System.Drawing.Image)(resources.GetObject("ImgUserImage.Image")));
            this.ImgUserImage.IsCircle = false;
            this.ImgUserImage.Location = new System.Drawing.Point(3, 3);
            this.ImgUserImage.Name = "ImgUserImage";
            this.ImgUserImage.Size = new System.Drawing.Size(58, 40);
            this.ImgUserImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.ImgUserImage.TabIndex = 0;
            this.ImgUserImage.TabStop = false;
            this.ImgUserImage.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // lblUsername
            // 
            this.lblUsername.AllowParentOverrides = false;
            this.lblUsername.AutoEllipsis = true;
            this.lblUsername.AutoSize = false;
            this.lblUsername.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblUsername.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblUsername.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUsername.EllipsisFormat = Bunifu.UI.WinForms.Ellipsis.EllipsisFormat.Path;
            this.lblUsername.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUsername.ForeColor = System.Drawing.Color.White;
            this.lblUsername.Location = new System.Drawing.Point(67, 3);
            this.lblUsername.Name = "lblUsername";
            this.lblUsername.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblUsername.Size = new System.Drawing.Size(91, 40);
            this.lblUsername.TabIndex = 1;
            this.lblUsername.Text = "User";
            this.lblUsername.TextAlignment = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblUsername.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BtnHome
            // 
            this.BtnHome.AllowAnimations = true;
            this.BtnHome.AllowMouseEffects = true;
            this.BtnHome.AllowToggling = false;
            this.BtnHome.AnimationSpeed = 200;
            this.BtnHome.AutoGenerateColors = false;
            this.BtnHome.AutoRoundBorders = false;
            this.BtnHome.AutoSizeLeftIcon = true;
            this.BtnHome.AutoSizeRightIcon = true;
            this.BtnHome.BackColor = System.Drawing.Color.Transparent;
            this.BtnHome.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnHome.BackgroundImage")));
            this.BtnHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHome.ButtonText = "Home";
            this.BtnHome.ButtonTextMarginLeft = 0;
            this.BtnHome.ColorContrastOnClick = 45;
            this.BtnHome.ColorContrastOnHover = 45;
            this.SidebarPanel.SetColumnSpan(this.BtnHome, 2);
            this.BtnHome.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.BtnHome.CustomizableEdges = borderEdges5;
            this.BtnHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnHome.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnHome.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnHome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BtnHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnHome.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnHome.ForeColor = System.Drawing.Color.White;
            this.BtnHome.IconLeft = null;
            this.BtnHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnHome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnHome.IconMarginLeft = 11;
            this.BtnHome.IconPadding = 10;
            this.BtnHome.IconRight = null;
            this.BtnHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnHome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnHome.IconSize = 25;
            this.BtnHome.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnHome.IdleBorderRadius = 0;
            this.BtnHome.IdleBorderThickness = 0;
            this.BtnHome.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnHome.IdleIconLeftImage = null;
            this.BtnHome.IdleIconRightImage = null;
            this.BtnHome.IndicateFocus = false;
            this.BtnHome.Location = new System.Drawing.Point(4, 50);
            this.BtnHome.Margin = new System.Windows.Forms.Padding(4);
            this.BtnHome.Name = "BtnHome";
            this.BtnHome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnHome.OnDisabledState.BorderRadius = 0;
            this.BtnHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHome.OnDisabledState.BorderThickness = 1;
            this.BtnHome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnHome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnHome.OnDisabledState.IconLeftImage = null;
            this.BtnHome.OnDisabledState.IconRightImage = null;
            this.BtnHome.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnHome.onHoverState.BorderRadius = 0;
            this.BtnHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHome.onHoverState.BorderThickness = 1;
            this.BtnHome.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.BtnHome.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnHome.onHoverState.IconLeftImage = null;
            this.BtnHome.onHoverState.IconRightImage = null;
            this.BtnHome.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnHome.OnIdleState.BorderRadius = 0;
            this.BtnHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHome.OnIdleState.BorderThickness = 1;
            this.BtnHome.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnHome.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnHome.OnIdleState.IconLeftImage = null;
            this.BtnHome.OnIdleState.IconRightImage = null;
            this.BtnHome.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnHome.OnPressedState.BorderRadius = 0;
            this.BtnHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHome.OnPressedState.BorderThickness = 1;
            this.BtnHome.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnHome.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnHome.OnPressedState.IconLeftImage = null;
            this.BtnHome.OnPressedState.IconRightImage = null;
            this.BtnHome.Size = new System.Drawing.Size(153, 38);
            this.BtnHome.TabIndex = 13;
            this.BtnHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnHome.TextMarginLeft = 0;
            this.BtnHome.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnHome.UseDefaultRadiusAndThickness = true;
            this.BtnHome.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // BtnEvents
            // 
            this.BtnEvents.AllowAnimations = true;
            this.BtnEvents.AllowMouseEffects = true;
            this.BtnEvents.AllowToggling = false;
            this.BtnEvents.AnimationSpeed = 200;
            this.BtnEvents.AutoGenerateColors = false;
            this.BtnEvents.AutoRoundBorders = false;
            this.BtnEvents.AutoSizeLeftIcon = true;
            this.BtnEvents.AutoSizeRightIcon = true;
            this.BtnEvents.BackColor = System.Drawing.Color.Transparent;
            this.BtnEvents.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnEvents.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnEvents.BackgroundImage")));
            this.BtnEvents.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEvents.ButtonText = "Voting Events";
            this.BtnEvents.ButtonTextMarginLeft = 0;
            this.BtnEvents.ColorContrastOnClick = 45;
            this.BtnEvents.ColorContrastOnHover = 45;
            this.SidebarPanel.SetColumnSpan(this.BtnEvents, 2);
            this.BtnEvents.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.BtnEvents.CustomizableEdges = borderEdges6;
            this.BtnEvents.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnEvents.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEvents.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnEvents.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnEvents.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BtnEvents.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnEvents.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnEvents.ForeColor = System.Drawing.Color.White;
            this.BtnEvents.IconLeft = null;
            this.BtnEvents.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnEvents.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEvents.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnEvents.IconMarginLeft = 11;
            this.BtnEvents.IconPadding = 10;
            this.BtnEvents.IconRight = null;
            this.BtnEvents.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnEvents.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnEvents.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnEvents.IconSize = 25;
            this.BtnEvents.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnEvents.IdleBorderRadius = 0;
            this.BtnEvents.IdleBorderThickness = 0;
            this.BtnEvents.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnEvents.IdleIconLeftImage = null;
            this.BtnEvents.IdleIconRightImage = null;
            this.BtnEvents.IndicateFocus = false;
            this.BtnEvents.Location = new System.Drawing.Point(4, 96);
            this.BtnEvents.Margin = new System.Windows.Forms.Padding(4);
            this.BtnEvents.Name = "BtnEvents";
            this.BtnEvents.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnEvents.OnDisabledState.BorderRadius = 0;
            this.BtnEvents.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEvents.OnDisabledState.BorderThickness = 1;
            this.BtnEvents.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnEvents.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnEvents.OnDisabledState.IconLeftImage = null;
            this.BtnEvents.OnDisabledState.IconRightImage = null;
            this.BtnEvents.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnEvents.onHoverState.BorderRadius = 0;
            this.BtnEvents.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEvents.onHoverState.BorderThickness = 1;
            this.BtnEvents.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.BtnEvents.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnEvents.onHoverState.IconLeftImage = null;
            this.BtnEvents.onHoverState.IconRightImage = null;
            this.BtnEvents.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnEvents.OnIdleState.BorderRadius = 0;
            this.BtnEvents.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEvents.OnIdleState.BorderThickness = 1;
            this.BtnEvents.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnEvents.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnEvents.OnIdleState.IconLeftImage = null;
            this.BtnEvents.OnIdleState.IconRightImage = null;
            this.BtnEvents.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnEvents.OnPressedState.BorderRadius = 0;
            this.BtnEvents.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnEvents.OnPressedState.BorderThickness = 1;
            this.BtnEvents.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnEvents.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnEvents.OnPressedState.IconLeftImage = null;
            this.BtnEvents.OnPressedState.IconRightImage = null;
            this.BtnEvents.Size = new System.Drawing.Size(153, 38);
            this.BtnEvents.TabIndex = 14;
            this.BtnEvents.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnEvents.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnEvents.TextMarginLeft = 0;
            this.BtnEvents.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnEvents.UseDefaultRadiusAndThickness = true;
            this.BtnEvents.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // BtnCandidates
            // 
            this.BtnCandidates.AllowAnimations = true;
            this.BtnCandidates.AllowMouseEffects = true;
            this.BtnCandidates.AllowToggling = false;
            this.BtnCandidates.AnimationSpeed = 200;
            this.BtnCandidates.AutoGenerateColors = false;
            this.BtnCandidates.AutoRoundBorders = false;
            this.BtnCandidates.AutoSizeLeftIcon = true;
            this.BtnCandidates.AutoSizeRightIcon = true;
            this.BtnCandidates.BackColor = System.Drawing.Color.Transparent;
            this.BtnCandidates.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnCandidates.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCandidates.BackgroundImage")));
            this.BtnCandidates.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCandidates.ButtonText = "Candidates";
            this.BtnCandidates.ButtonTextMarginLeft = 0;
            this.BtnCandidates.ColorContrastOnClick = 45;
            this.BtnCandidates.ColorContrastOnHover = 45;
            this.SidebarPanel.SetColumnSpan(this.BtnCandidates, 2);
            this.BtnCandidates.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.BtnCandidates.CustomizableEdges = borderEdges7;
            this.BtnCandidates.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCandidates.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCandidates.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnCandidates.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnCandidates.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BtnCandidates.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCandidates.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCandidates.ForeColor = System.Drawing.Color.White;
            this.BtnCandidates.IconLeft = null;
            this.BtnCandidates.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCandidates.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCandidates.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCandidates.IconMarginLeft = 11;
            this.BtnCandidates.IconPadding = 10;
            this.BtnCandidates.IconRight = null;
            this.BtnCandidates.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCandidates.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCandidates.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCandidates.IconSize = 25;
            this.BtnCandidates.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnCandidates.IdleBorderRadius = 0;
            this.BtnCandidates.IdleBorderThickness = 0;
            this.BtnCandidates.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnCandidates.IdleIconLeftImage = null;
            this.BtnCandidates.IdleIconRightImage = null;
            this.BtnCandidates.IndicateFocus = false;
            this.BtnCandidates.Location = new System.Drawing.Point(4, 142);
            this.BtnCandidates.Margin = new System.Windows.Forms.Padding(4);
            this.BtnCandidates.Name = "BtnCandidates";
            this.BtnCandidates.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCandidates.OnDisabledState.BorderRadius = 0;
            this.BtnCandidates.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCandidates.OnDisabledState.BorderThickness = 1;
            this.BtnCandidates.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCandidates.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCandidates.OnDisabledState.IconLeftImage = null;
            this.BtnCandidates.OnDisabledState.IconRightImage = null;
            this.BtnCandidates.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnCandidates.onHoverState.BorderRadius = 0;
            this.BtnCandidates.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCandidates.onHoverState.BorderThickness = 1;
            this.BtnCandidates.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.BtnCandidates.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnCandidates.onHoverState.IconLeftImage = null;
            this.BtnCandidates.onHoverState.IconRightImage = null;
            this.BtnCandidates.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnCandidates.OnIdleState.BorderRadius = 0;
            this.BtnCandidates.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCandidates.OnIdleState.BorderThickness = 1;
            this.BtnCandidates.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnCandidates.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCandidates.OnIdleState.IconLeftImage = null;
            this.BtnCandidates.OnIdleState.IconRightImage = null;
            this.BtnCandidates.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnCandidates.OnPressedState.BorderRadius = 0;
            this.BtnCandidates.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCandidates.OnPressedState.BorderThickness = 1;
            this.BtnCandidates.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnCandidates.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnCandidates.OnPressedState.IconLeftImage = null;
            this.BtnCandidates.OnPressedState.IconRightImage = null;
            this.BtnCandidates.Size = new System.Drawing.Size(153, 38);
            this.BtnCandidates.TabIndex = 15;
            this.BtnCandidates.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCandidates.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCandidates.TextMarginLeft = 0;
            this.BtnCandidates.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCandidates.UseDefaultRadiusAndThickness = true;
            this.BtnCandidates.Click += new System.EventHandler(this.bunifuButton4_Click);
            // 
            // BtnVoters
            // 
            this.BtnVoters.AllowAnimations = true;
            this.BtnVoters.AllowMouseEffects = true;
            this.BtnVoters.AllowToggling = false;
            this.BtnVoters.AnimationSpeed = 200;
            this.BtnVoters.AutoGenerateColors = false;
            this.BtnVoters.AutoRoundBorders = false;
            this.BtnVoters.AutoSizeLeftIcon = true;
            this.BtnVoters.AutoSizeRightIcon = true;
            this.BtnVoters.BackColor = System.Drawing.Color.Transparent;
            this.BtnVoters.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnVoters.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnVoters.BackgroundImage")));
            this.BtnVoters.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVoters.ButtonText = "Voters";
            this.BtnVoters.ButtonTextMarginLeft = 0;
            this.BtnVoters.ColorContrastOnClick = 45;
            this.BtnVoters.ColorContrastOnHover = 45;
            this.SidebarPanel.SetColumnSpan(this.BtnVoters, 2);
            this.BtnVoters.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.BtnVoters.CustomizableEdges = borderEdges8;
            this.BtnVoters.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnVoters.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnVoters.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnVoters.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnVoters.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BtnVoters.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnVoters.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnVoters.ForeColor = System.Drawing.Color.White;
            this.BtnVoters.IconLeft = null;
            this.BtnVoters.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnVoters.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnVoters.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnVoters.IconMarginLeft = 11;
            this.BtnVoters.IconPadding = 10;
            this.BtnVoters.IconRight = null;
            this.BtnVoters.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnVoters.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnVoters.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnVoters.IconSize = 25;
            this.BtnVoters.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnVoters.IdleBorderRadius = 0;
            this.BtnVoters.IdleBorderThickness = 0;
            this.BtnVoters.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnVoters.IdleIconLeftImage = null;
            this.BtnVoters.IdleIconRightImage = null;
            this.BtnVoters.IndicateFocus = false;
            this.BtnVoters.Location = new System.Drawing.Point(4, 188);
            this.BtnVoters.Margin = new System.Windows.Forms.Padding(4);
            this.BtnVoters.Name = "BtnVoters";
            this.BtnVoters.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnVoters.OnDisabledState.BorderRadius = 0;
            this.BtnVoters.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVoters.OnDisabledState.BorderThickness = 1;
            this.BtnVoters.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnVoters.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnVoters.OnDisabledState.IconLeftImage = null;
            this.BtnVoters.OnDisabledState.IconRightImage = null;
            this.BtnVoters.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnVoters.onHoverState.BorderRadius = 0;
            this.BtnVoters.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVoters.onHoverState.BorderThickness = 1;
            this.BtnVoters.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.BtnVoters.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnVoters.onHoverState.IconLeftImage = null;
            this.BtnVoters.onHoverState.IconRightImage = null;
            this.BtnVoters.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnVoters.OnIdleState.BorderRadius = 0;
            this.BtnVoters.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVoters.OnIdleState.BorderThickness = 1;
            this.BtnVoters.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnVoters.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnVoters.OnIdleState.IconLeftImage = null;
            this.BtnVoters.OnIdleState.IconRightImage = null;
            this.BtnVoters.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnVoters.OnPressedState.BorderRadius = 0;
            this.BtnVoters.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnVoters.OnPressedState.BorderThickness = 1;
            this.BtnVoters.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnVoters.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnVoters.OnPressedState.IconLeftImage = null;
            this.BtnVoters.OnPressedState.IconRightImage = null;
            this.BtnVoters.Size = new System.Drawing.Size(153, 38);
            this.BtnVoters.TabIndex = 16;
            this.BtnVoters.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnVoters.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnVoters.TextMarginLeft = 0;
            this.BtnVoters.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnVoters.UseDefaultRadiusAndThickness = true;
            this.BtnVoters.Click += new System.EventHandler(this.bunifuButton5_Click);
            // 
            // BtnResults
            // 
            this.BtnResults.AllowAnimations = true;
            this.BtnResults.AllowMouseEffects = true;
            this.BtnResults.AllowToggling = false;
            this.BtnResults.AnimationSpeed = 200;
            this.BtnResults.AutoGenerateColors = false;
            this.BtnResults.AutoRoundBorders = false;
            this.BtnResults.AutoSizeLeftIcon = true;
            this.BtnResults.AutoSizeRightIcon = true;
            this.BtnResults.BackColor = System.Drawing.Color.Transparent;
            this.BtnResults.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnResults.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnResults.BackgroundImage")));
            this.BtnResults.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnResults.ButtonText = "Results";
            this.BtnResults.ButtonTextMarginLeft = 0;
            this.BtnResults.ColorContrastOnClick = 45;
            this.BtnResults.ColorContrastOnHover = 45;
            this.SidebarPanel.SetColumnSpan(this.BtnResults, 2);
            this.BtnResults.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.BtnResults.CustomizableEdges = borderEdges9;
            this.BtnResults.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnResults.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnResults.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnResults.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnResults.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BtnResults.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnResults.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnResults.ForeColor = System.Drawing.Color.White;
            this.BtnResults.IconLeft = null;
            this.BtnResults.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnResults.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnResults.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnResults.IconMarginLeft = 11;
            this.BtnResults.IconPadding = 10;
            this.BtnResults.IconRight = null;
            this.BtnResults.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnResults.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnResults.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnResults.IconSize = 25;
            this.BtnResults.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnResults.IdleBorderRadius = 0;
            this.BtnResults.IdleBorderThickness = 0;
            this.BtnResults.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnResults.IdleIconLeftImage = null;
            this.BtnResults.IdleIconRightImage = null;
            this.BtnResults.IndicateFocus = false;
            this.BtnResults.Location = new System.Drawing.Point(4, 234);
            this.BtnResults.Margin = new System.Windows.Forms.Padding(4);
            this.BtnResults.Name = "BtnResults";
            this.BtnResults.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnResults.OnDisabledState.BorderRadius = 0;
            this.BtnResults.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnResults.OnDisabledState.BorderThickness = 1;
            this.BtnResults.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnResults.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnResults.OnDisabledState.IconLeftImage = null;
            this.BtnResults.OnDisabledState.IconRightImage = null;
            this.BtnResults.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnResults.onHoverState.BorderRadius = 0;
            this.BtnResults.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnResults.onHoverState.BorderThickness = 1;
            this.BtnResults.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.BtnResults.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnResults.onHoverState.IconLeftImage = null;
            this.BtnResults.onHoverState.IconRightImage = null;
            this.BtnResults.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnResults.OnIdleState.BorderRadius = 0;
            this.BtnResults.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnResults.OnIdleState.BorderThickness = 1;
            this.BtnResults.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnResults.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnResults.OnIdleState.IconLeftImage = null;
            this.BtnResults.OnIdleState.IconRightImage = null;
            this.BtnResults.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnResults.OnPressedState.BorderRadius = 0;
            this.BtnResults.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnResults.OnPressedState.BorderThickness = 1;
            this.BtnResults.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnResults.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnResults.OnPressedState.IconLeftImage = null;
            this.BtnResults.OnPressedState.IconRightImage = null;
            this.BtnResults.Size = new System.Drawing.Size(153, 38);
            this.BtnResults.TabIndex = 17;
            this.BtnResults.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnResults.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnResults.TextMarginLeft = 0;
            this.BtnResults.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnResults.UseDefaultRadiusAndThickness = true;
            this.BtnResults.Click += new System.EventHandler(this.bunifuButton6_Click);
            // 
            // BtnSettings
            // 
            this.BtnSettings.AllowAnimations = true;
            this.BtnSettings.AllowMouseEffects = true;
            this.BtnSettings.AllowToggling = false;
            this.BtnSettings.AnimationSpeed = 200;
            this.BtnSettings.AutoGenerateColors = false;
            this.BtnSettings.AutoRoundBorders = false;
            this.BtnSettings.AutoSizeLeftIcon = true;
            this.BtnSettings.AutoSizeRightIcon = true;
            this.BtnSettings.BackColor = System.Drawing.Color.Transparent;
            this.BtnSettings.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.BtnSettings.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnSettings.BackgroundImage")));
            this.BtnSettings.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSettings.ButtonText = "Settings";
            this.BtnSettings.ButtonTextMarginLeft = 0;
            this.BtnSettings.ColorContrastOnClick = 45;
            this.BtnSettings.ColorContrastOnHover = 45;
            this.SidebarPanel.SetColumnSpan(this.BtnSettings, 2);
            this.BtnSettings.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.BtnSettings.CustomizableEdges = borderEdges10;
            this.BtnSettings.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnSettings.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSettings.DisabledFillColor = System.Drawing.Color.Empty;
            this.BtnSettings.DisabledForecolor = System.Drawing.Color.Empty;
            this.BtnSettings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BtnSettings.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnSettings.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnSettings.ForeColor = System.Drawing.Color.White;
            this.BtnSettings.IconLeft = null;
            this.BtnSettings.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnSettings.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSettings.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnSettings.IconMarginLeft = 11;
            this.BtnSettings.IconPadding = 10;
            this.BtnSettings.IconRight = null;
            this.BtnSettings.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnSettings.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnSettings.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnSettings.IconSize = 25;
            this.BtnSettings.IdleBorderColor = System.Drawing.Color.Empty;
            this.BtnSettings.IdleBorderRadius = 0;
            this.BtnSettings.IdleBorderThickness = 0;
            this.BtnSettings.IdleFillColor = System.Drawing.Color.Empty;
            this.BtnSettings.IdleIconLeftImage = null;
            this.BtnSettings.IdleIconRightImage = null;
            this.BtnSettings.IndicateFocus = false;
            this.BtnSettings.Location = new System.Drawing.Point(4, 280);
            this.BtnSettings.Margin = new System.Windows.Forms.Padding(4);
            this.BtnSettings.Name = "BtnSettings";
            this.BtnSettings.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnSettings.OnDisabledState.BorderRadius = 0;
            this.BtnSettings.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSettings.OnDisabledState.BorderThickness = 1;
            this.BtnSettings.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnSettings.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnSettings.OnDisabledState.IconLeftImage = null;
            this.BtnSettings.OnDisabledState.IconRightImage = null;
            this.BtnSettings.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnSettings.onHoverState.BorderRadius = 0;
            this.BtnSettings.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSettings.onHoverState.BorderThickness = 1;
            this.BtnSettings.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.BtnSettings.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(190)))), ((int)(((byte)(235)))));
            this.BtnSettings.onHoverState.IconLeftImage = null;
            this.BtnSettings.onHoverState.IconRightImage = null;
            this.BtnSettings.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.BtnSettings.OnIdleState.BorderRadius = 0;
            this.BtnSettings.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSettings.OnIdleState.BorderThickness = 1;
            this.BtnSettings.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.BtnSettings.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnSettings.OnIdleState.IconLeftImage = null;
            this.BtnSettings.OnIdleState.IconRightImage = null;
            this.BtnSettings.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnSettings.OnPressedState.BorderRadius = 0;
            this.BtnSettings.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnSettings.OnPressedState.BorderThickness = 1;
            this.BtnSettings.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(12)))), ((int)(((byte)(59)))), ((int)(((byte)(94)))));
            this.BtnSettings.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnSettings.OnPressedState.IconLeftImage = null;
            this.BtnSettings.OnPressedState.IconRightImage = null;
            this.BtnSettings.Size = new System.Drawing.Size(153, 38);
            this.BtnSettings.TabIndex = 18;
            this.BtnSettings.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnSettings.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnSettings.TextMarginLeft = 0;
            this.BtnSettings.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnSettings.UseDefaultRadiusAndThickness = true;
            this.BtnSettings.Click += new System.EventHandler(this.bunifuButton7_Click);
            // 
            // IcoLogo
            // 
            this.IcoLogo.AllowAnimations = true;
            this.IcoLogo.AllowBorderColorChanges = true;
            this.IcoLogo.AllowMouseEffects = true;
            this.IcoLogo.AnimationSpeed = 200;
            this.IcoLogo.BackColor = System.Drawing.Color.Transparent;
            this.IcoLogo.BackgroundColor = System.Drawing.Color.Transparent;
            this.IcoLogo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.IcoLogo.BorderColor = System.Drawing.Color.Transparent;
            this.IcoLogo.BorderRadius = 0;
            this.IcoLogo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.IcoLogo.BorderThickness = 0;
            this.IcoLogo.ColorContrastOnClick = 30;
            this.IcoLogo.ColorContrastOnHover = 30;
            this.IcoLogo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.IcoLogo.CustomizableEdges = borderEdges1;
            this.IcoLogo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.IcoLogo.Dock = System.Windows.Forms.DockStyle.Left;
            this.IcoLogo.Image = global::alphaVote.Properties.Resources.logo;
            this.IcoLogo.ImageMargin = new System.Windows.Forms.Padding(0);
            this.IcoLogo.Location = new System.Drawing.Point(8, 8);
            this.IcoLogo.Margin = new System.Windows.Forms.Padding(8);
            this.IcoLogo.Name = "IcoLogo";
            this.IcoLogo.RoundBorders = false;
            this.IcoLogo.ShowBorders = false;
            this.IcoLogo.Size = new System.Drawing.Size(26, 25);
            this.IcoLogo.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Flat;
            this.IcoLogo.TabIndex = 13;
            this.IcoLogo.TabStop = false;
            // 
            // BtnMinimize
            // 
            this.BtnMinimize.AllowAnimations = true;
            this.BtnMinimize.AllowBorderColorChanges = true;
            this.BtnMinimize.AllowMouseEffects = true;
            this.BtnMinimize.AnimationSpeed = 200;
            this.BtnMinimize.BackColor = System.Drawing.Color.Transparent;
            this.BtnMinimize.BackgroundColor = System.Drawing.Color.Transparent;
            this.BtnMinimize.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.BtnMinimize.BorderColor = System.Drawing.Color.Transparent;
            this.BtnMinimize.BorderRadius = 0;
            this.BtnMinimize.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.BtnMinimize.BorderThickness = 0;
            this.BtnMinimize.ColorContrastOnClick = 30;
            this.BtnMinimize.ColorContrastOnHover = 30;
            this.BtnMinimize.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnMinimize.CustomizableEdges = borderEdges2;
            this.BtnMinimize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnMinimize.Dock = System.Windows.Forms.DockStyle.Right;
            this.BtnMinimize.Image = global::alphaVote.Properties.Resources.minimize1;
            this.BtnMinimize.ImageMargin = new System.Windows.Forms.Padding(0);
            this.BtnMinimize.Location = new System.Drawing.Point(759, 4);
            this.BtnMinimize.Margin = new System.Windows.Forms.Padding(4);
            this.BtnMinimize.Name = "BtnMinimize";
            this.BtnMinimize.RoundBorders = false;
            this.BtnMinimize.ShowBorders = false;
            this.BtnMinimize.Size = new System.Drawing.Size(34, 33);
            this.BtnMinimize.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Flat;
            this.BtnMinimize.TabIndex = 11;
            this.BtnMinimize.TabStop = false;
            this.BtnMinimize.Click += new System.EventHandler(this.bunifuIconButton2_Click);
            this.BtnMinimize.MouseHover += new System.EventHandler(this.bunifuIconButton2_MouseHover);
            // 
            // BtnExit
            // 
            this.BtnExit.AllowAnimations = true;
            this.BtnExit.AllowBorderColorChanges = true;
            this.BtnExit.AllowMouseEffects = true;
            this.BtnExit.AnimationSpeed = 200;
            this.BtnExit.BackColor = System.Drawing.Color.Transparent;
            this.BtnExit.BackgroundColor = System.Drawing.Color.Transparent;
            this.BtnExit.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.BtnExit.BorderColor = System.Drawing.Color.Transparent;
            this.BtnExit.BorderRadius = 0;
            this.BtnExit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.BtnExit.BorderThickness = 0;
            this.BtnExit.ColorContrastOnClick = 30;
            this.BtnExit.ColorContrastOnHover = 30;
            this.BtnExit.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnExit.CustomizableEdges = borderEdges3;
            this.BtnExit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnExit.Dock = System.Windows.Forms.DockStyle.Right;
            this.BtnExit.Image = global::alphaVote.Properties.Resources.cancel;
            this.BtnExit.ImageMargin = new System.Windows.Forms.Padding(0);
            this.BtnExit.Location = new System.Drawing.Point(801, 4);
            this.BtnExit.Margin = new System.Windows.Forms.Padding(4);
            this.BtnExit.Name = "BtnExit";
            this.BtnExit.RoundBorders = false;
            this.BtnExit.ShowBorders = false;
            this.BtnExit.Size = new System.Drawing.Size(34, 33);
            this.BtnExit.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Flat;
            this.BtnExit.TabIndex = 10;
            this.BtnExit.TabStop = false;
            this.BtnExit.Click += new System.EventHandler(this.bunifuIconButton1_Click);
            this.BtnExit.MouseHover += new System.EventHandler(this.bunifuIconButton1_MouseHover);
            // 
            // bunifuFormDock2
            // 
            this.bunifuFormDock2.AllowFormDragging = true;
            this.bunifuFormDock2.AllowFormDropShadow = true;
            this.bunifuFormDock2.AllowFormResizing = true;
            this.bunifuFormDock2.AllowHidingBottomRegion = true;
            this.bunifuFormDock2.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock2.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock2.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock2.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock2.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock2.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock2.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock2.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock2.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock2.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock2.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock2.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock2.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock2.ContainerControl = this;
            this.bunifuFormDock2.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock2.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock2.DockingOptions.DockAll = true;
            this.bunifuFormDock2.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock2.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock2.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock2.DockingOptions.DockLeft = true;
            this.bunifuFormDock2.DockingOptions.DockRight = true;
            this.bunifuFormDock2.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock2.DockingOptions.DockTopRight = true;
            this.bunifuFormDock2.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock2.ParentForm = this;
            this.bunifuFormDock2.ShowCursorChanges = true;
            this.bunifuFormDock2.ShowDockingIndicators = true;
            this.bunifuFormDock2.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock2.TitleBarOptions.BunifuFormDock = this.bunifuFormDock2;
            this.bunifuFormDock2.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock2.TitleBarOptions.TitleBarControl = this.IcoLogo;
            this.bunifuFormDock2.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // TitleBarPanel
            // 
            this.TitleBarPanel.ColumnCount = 4;
            this.TitleBarPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.TitleBarPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TitleBarPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.TitleBarPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 42F));
            this.TitleBarPanel.Controls.Add(this.lblTitle, 1, 0);
            this.TitleBarPanel.Controls.Add(this.IcoLogo, 0, 0);
            this.TitleBarPanel.Controls.Add(this.BtnMinimize, 2, 0);
            this.TitleBarPanel.Controls.Add(this.BtnExit, 3, 0);
            this.TitleBarPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.TitleBarPanel.Location = new System.Drawing.Point(0, 0);
            this.TitleBarPanel.Name = "TitleBarPanel";
            this.TitleBarPanel.RowCount = 1;
            this.TitleBarPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TitleBarPanel.Size = new System.Drawing.Size(839, 41);
            this.TitleBarPanel.TabIndex = 15;
            // 
            // HomePagePanel
            // 
            this.HomePagePanel.BackColor = System.Drawing.Color.Transparent;
            this.HomePagePanel.ColumnCount = 2;
            this.HomePagePanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.HomePagePanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.HomePagePanel.Controls.Add(this.bunifuPanel4, 1, 2);
            this.HomePagePanel.Controls.Add(this.bunifuPanel3, 0, 2);
            this.HomePagePanel.Controls.Add(this.bunifuPanel1, 0, 0);
            this.HomePagePanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HomePagePanel.Location = new System.Drawing.Point(3, 3);
            this.HomePagePanel.Name = "HomePagePanel";
            this.HomePagePanel.RowCount = 4;
            this.HomePagePanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.HomePagePanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.HomePagePanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.HomePagePanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.HomePagePanel.Size = new System.Drawing.Size(607, 358);
            this.HomePagePanel.TabIndex = 0;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.HomePagePanel.SetColumnSpan(this.bunifuPanel1, 2);
            this.bunifuPanel1.Controls.Add(this.bunifuPanel2);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(3, 3);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.HomePagePanel.SetRowSpan(this.bunifuPanel1, 2);
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(601, 172);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(49)))), ((int)(((byte)(56)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 8;
            this.bunifuPanel2.BorderThickness = 0;
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(8);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = false;
            this.bunifuPanel2.Size = new System.Drawing.Size(601, 172);
            this.bunifuPanel2.TabIndex = 1;
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(49)))), ((int)(((byte)(56)))));
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 8;
            this.bunifuPanel3.BorderThickness = 0;
            this.bunifuPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel3.Location = new System.Drawing.Point(8, 186);
            this.bunifuPanel3.Margin = new System.Windows.Forms.Padding(8);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.HomePagePanel.SetRowSpan(this.bunifuPanel3, 2);
            this.bunifuPanel3.ShowBorders = false;
            this.bunifuPanel3.Size = new System.Drawing.Size(287, 164);
            this.bunifuPanel3.TabIndex = 1;
            // 
            // bunifuPanel4
            // 
            this.bunifuPanel4.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(49)))), ((int)(((byte)(56)))));
            this.bunifuPanel4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel4.BackgroundImage")));
            this.bunifuPanel4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel4.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel4.BorderRadius = 8;
            this.bunifuPanel4.BorderThickness = 0;
            this.bunifuPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel4.Location = new System.Drawing.Point(311, 186);
            this.bunifuPanel4.Margin = new System.Windows.Forms.Padding(8);
            this.bunifuPanel4.Name = "bunifuPanel4";
            this.HomePagePanel.SetRowSpan(this.bunifuPanel4, 2);
            this.bunifuPanel4.ShowBorders = false;
            this.bunifuPanel4.Size = new System.Drawing.Size(288, 164);
            this.bunifuPanel4.TabIndex = 2;
            // 
            // tabPage6
            // 
            this.tabPage6.Location = new System.Drawing.Point(23, 4);
            this.tabPage6.Name = "tabPage6";
            this.tabPage6.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage6.Size = new System.Drawing.Size(613, 364);
            this.tabPage6.TabIndex = 5;
            this.tabPage6.Text = "tabPage6";
            this.tabPage6.UseVisualStyleBackColor = true;
            // 
            // FrmDashboard
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(21)))), ((int)(((byte)(28)))), ((int)(((byte)(38)))));
            this.ClientSize = new System.Drawing.Size(839, 450);
            this.ControlBox = false;
            this.Controls.Add(this.TitleBarPanel);
            this.Controls.Add(this.BodyPanel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FrmDashboard";
            this.Text = "Alpha Vote";
            this.Load += new System.EventHandler(this.FrmDashboard_Load);
            this.BodyPanel.ResumeLayout(false);
            this.bunifuPages1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.SidebarPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ImgUserImage)).EndInit();
            this.TitleBarPanel.ResumeLayout(false);
            this.HomePagePanel.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.TableLayoutPanel BodyPanel;
        private Bunifu.UI.WinForms.BunifuPages bunifuPages1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TableLayoutPanel SidebarPanel;
        private Bunifu.UI.WinForms.BunifuPictureBox ImgUserImage;
        private Bunifu.UI.WinForms.BunifuLabel lblUsername;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton BtnExit;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.TabPage tabPage5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnSettings;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnHome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnEvents;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCandidates;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnVoters;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnResults;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnLogout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton BtnMinimize;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton IcoLogo;
        private Bunifu.UI.WinForms.BunifuLabel lblTitle;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock2;
        private System.Windows.Forms.TableLayoutPanel TitleBarPanel;
        private System.Windows.Forms.TableLayoutPanel HomePagePanel;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel4;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private System.Windows.Forms.TabPage tabPage6;
    }
}